### ISSUE TITLE
rollup v0.64.1 React App doesn`t open

### ISSUE THREAD

**Issue by dorobiro** [sbayd/react-cv#26]
Hi sbayd,

after installing npm and then npm start, I get the following message and the app does not open:

rollup v0.64.1
bundles src/index.js → dist\index.js, dist\index.es.js...
created dist\index.js, dist\index.es.js in 5.1s

[2022-04-29 18:50:03] waiting for changes...

What can be done in that case?

I am working on Windows 11 Pro --> Visual Studio Code
Version: 1.66.2 (user setup)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

Thank you in advance for your support!

Br
Doro

**Comment by sbayd** [comment]
Helo, 

Sorry for the late reply, I wasn't maintaining this library for a while. 

I've replaced the whole build system with a simple parcel config. It should work as expected.
