### ISSUE TITLE
Version 1.5.1 Issue with marked

### ISSUE THREAD

**Issue by anyderre** [sbayd/react-cv#39]
export 'default' (imported as '$5OpyM$marked') was not found in 'marked' (possible exports: Hooks, Lexer, Marked, Parser, Renderer, TextRenderer, Tokenizer, defaults, getDefaults, lexer, marked, options, parse, parseInline, parser, setOptions, use, walkTokens)

**Comment by sbayd** [comment]
Thanks, it seems I made an error during the publishing process. It should be fixed on 1.6.0
